### PR TITLE
init content for ADB remote project

### PR DESCRIPTION
**Pull request by annabauza**
## Init remote controller support following add commands:
- back button
- menu button
- adb reverse tcp:8081 tcp:8081
- all available directions for DPAD plus centre button
- player buttons (prev, rw, play/pause, ff, next)

## Preview:
adb-remote

### Why to use ADB-remote?
- standard android emulator remote covers loads of AndroidTV emulator
standard-adb
- it has build in `adb reverse tcp:8081 tcp:8081` - very useful for react native developers
- it has diagonal arrow
- it has next and prev for testing players
- it connects to real device via adb, so keys not supported by device can be tested

### Compiling remote adb require:
- Mac OS v. `10.15 Catalina` is expected to release around Monday 23 September 2019, until then there is beta version,
- XCode 11,
- adb located in `~/Library/Android/sdk/platform-tools/adb` if your path to adb is different please change it in `Utils.swift` class.
- there can be only one instance of connected adb device

### How to use:
- Start emulator or connect your device via adb (important: only one at a time)
- Open this project in XCode and run
- The remote is now ready to use.

### CODE REVIEW

**Comment by ranmeirman** [comment]
@annabauza it looks good. I am missing how to use and install

**Comment by annabauza** [comment]
good point Ran, thanks

**Comment by annabauza** [comment]
@ranmeirman I have made the changes you suggest, you mind to review?

**Comment by ranmeirman** [comment]
It is a bit problematic that it works on on Catalina and xcode 11 which is still in beta. 
I also think we should have the ability to run it without the need of xcode, you can merge it if you want

**Comment by annabauza** [comment]
We can't go down because it is written in swift UI, we can wait 3 weeks though. Maybe we could store the app in App Center, but then I'm not sure do we need certificate, I don't have any. @liviur @snooky23  ?

**Pull request merged**
